name: Build & Push Docker Image
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 8 * *'
env:
  image: andygodish/gh-runner-debian
  tag: 12-slim
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build image
      run: docker build -t ${{ env.image }}:${{ env.tag }} .

    - name: Push image
      run: docker push ${{ env.image }}:${{ env.tag }}